"""Writes ../design_report_C7.md from summary_C7.json (+ the sensitivity summaries)."""
import json, os, csv
HERE = os.path.dirname(os.path.abspath(__file__)); OUT = os.path.join(HERE, '..')
S = json.load(open(os.path.join(HERE, 'summary_C7.json')))
SP, SR, SC, DG, RD = S['sections']['prim'], S['sections']['raft'], S['sections']['col'], S['sections']['brace'], S['sections']['rod']
S7 = json.load(open(os.path.join(HERE, 'summary_C7_heavy.json'))); S7b = json.load(open(os.path.join(HERE, 'summary_C7_light.json')))
S6 = json.load(open(os.path.join(HERE, '..', '..', 'C', 'calc', 'summary_C.json')))
SZ = json.load(open(os.path.join(HERE, 'summary_C7_ze127.json'))); SW = json.load(open(os.path.join(HERE, 'summary_C7_wall10.json')))
f = lambda x, n=1: '%.*f' % (n, x)
W, L, B = S['weight'], S['lengths'], S['bays']
Ls = []
A = Ls.append
A('# Design report - alternative C, design Rev 8: reduced roofed area, economic scheme (2026-09-29)\n')
A('**Status: design complete, no detailing (brief Rev 8). Basis for the next offer revision.** Supersedes design Rev 7 / 7b: same reduced roof extent, loads (load basis Rev 3), base type and drainage; new economic scheme (section 1a). Re-run: `python3 calc/run_rev7.py; python3 calc/write_report_rev8.py` (Rev 7 heavy set: `SCHEME=nested ECON=0 SEC_PRIM="IPE 300" SEC_RAFT="IPE 240" PRIM_TOP_OFFSET=0.03 SPAN_SECTION=...`).\n')
A('## 1. What changed and why\n')
A("The architect's 2nd-level plan (ALWATD sheet A_103, 29 Sep 2026) encloses only the west block and the north part of the east block; the SW terrace, the south strip of the east wing with the pyramid skylight (our former \"elevator\" opening) and the stair well stay open. The client adopted this reduced area (brief Rev 8). The roof boundary is put on existing column lines so that no new gravity column is needed:\n")
A('| | Rev 6a | Rev 7 |\n|---|---|---|')
A('| Roof boundary | whole L-shape x 67.89-95.69, y 15.57-35.87 less the notch and two wells | west block x 67.89-77.89 / y 21.66-35.37 (south face on the K19-K20 line); east block x 77.89-95.69 / y 24.36-35.87 (south face on the K16-K17-K18 line); stair well open |')
A('| Roofed area | %s m2 | **%s m2** (architect\'s note: 300 m2) |' % (f(S6['roof_area'], 0), f(S['roof_area'], 0)))
A('| Steel columns | 27 (K1-K27) + WP1 | **20 (K1-K20)** + wind posts WP2, WP3 (13.7 m south eave of the east block) and WP4 (9.8 m south eave of the west block) |')
A('| Wall braced bays | 8 (B1-B7, B9) | **6**: B1 K1-K2, B2 K5-K7, B3 K16-K17 (E-W); B5 K15-K19, B6 K4-K14, B7 K16-K20 (N-S) |')
A('| Roof rod panels | 13 in 5 strips | **12 in 6 strips** (RT-N-W 2, RT-N-E 3, RT-JOG 1, RT-W 3, RT-SW 1, RT-E 2) |')
A('| Longest primary | P13 K19-K20 9.8 m IPE 330 | P_K17K18 K17-K18 **13.7 m IPE 330** (south eave of the east block, no column between K17 and K18); P13 9.8 m IPE 330 |')
A('| Roof edge heights above the slab | north 3.33, south 4.55 m | north %s, south-west edge (y 21.66) %s, south-east edge (y 24.36) %s m |' % (f(S['clear']['north_eave'], 2), f(S['clear']['south_west_edge'], 2), f(S['clear']['south_east_edge'], 2)))
A('| Steel for the offer | 22.2 t (incl. 1.6 t girts) | **%s t** without girts (%s t with girts); Rev 7 heavy set %s t |' % (f(W['total_offer']/1000, 1), f(W['total_with_girts']/1000, 1), f(S7['weight']['total_offer']/1000, 1)))
A('')
A("Design choices to note for the architect and the client:\n")
A("- The west block's south wall sits on the K19-K20 column line (y 21.66 outer face), 1.7 m north of the existing terrace wall line (y 19.97) drawn by the architect. Putting the roof edge on the existing wall line would need three gravity posts on the slab (no concrete column there) or 1.8 m rafter cantilevers through the flush fin-plate framing; both were rejected for simplicity and for the no-new-columns rule. The 1.7 m strip stays open terrace (about 17 m2).")
A("- The east block's south wall sits on the K16-K17-K18 line (y 24.36 outer face), 0.7-0.9 m south of the architect's corridor wall, which gains a wider corridor. The three 0.20 m posts the architect drew on this wall at 4 m spacing do not exist as concrete columns; the design uses two wind posts WP2/WP3 (HEA 140, shear only, anchored on the slab like WP1 was) and one 13.7 m IPE 330 eave beam between K17 and K18.")
A("- Braced bay B6 moved from K14-K18 (now the lift lobby) to K4-K14 on the east wall north of the corridor; B3 sits in the blank wall above the skylight (K16-K17); B7 is the 2.7 m wide bay K16-K20 on the light-well face (steep X: 1.5 x H uplift, checked). The bays B1 K1-K2, B2 K5-K7, B3 K16-K17, B5 K15-K19, B6 K4-K14 and B7 K16-K20 must stay free of doors and windows; B4, B9 and the old B6 are gone.")
A("- Openings: the stair well keeps its trimmers, upstand and flashing on P_K10K11, R78 and R82; the light well no longer needs T2 or an upstand (it is outside the roof). The south roof edges get a verge flashing and a fascia; there is no gutter on them (the roof still falls north).")
A('')
A('## 1a. Economic scheme (Rev 8) and what it saves\n')
A('The column grid gives rafter spans of 4.8-7.6 m instead of the 9.2 m of the full roof, so the Rev 6a section set was under-used (rafters 0.38, primaries 0.24). Rev 8 changes the framing scheme to exploit that:\n')
A('- **Rafters continuous over the y 29.3 primaries and seated on top of the primaries** (bottom flange bolted to the primary top flange with 2 M16, no fin plates, no coped webs). Continuity halves the long-span deflection and moves the peak moment to the support: rafters **%s** (west lines 13.7 m long, one bolted splice at the low-moment point; east lines 11.5 m from one bar).' % SR)
A('- Primaries no longer have to be deeper than the rafters: **%s** for the 4.1-5.7 m spans; the two long eave beams (13.7 m and 9.8 m) stay **IPE 330**, cut from two 12 m bars without offcut (12 + 1.7 and 9.8).' % SP)
A('- Roof plane raised to TOS = %s + 0.06 (35.87 - y) so the 3.00 m clear height under the cap-plate nuts at the north eave is kept (%s m); columns are shorter under the shallower primaries (K1 %s m, K19 %s m).' % (f(S['TOS0'], 2), f(S['clear']['cap_nuts'], 2), f(S['clear']['L_K1'], 3), f(S['clear']['L_K19'], 3)))
A('- Wall diagonals **%s** with M16 bolts at the 35 mm gauge, roof rods **%s**; purlins Z200x2.0 at 1.5 m and columns HEA 140 unchanged.' % (DG, RD))
A('- Bases, drainage, wind posts and the six braced bays are unchanged from Rev 7.')
A('')
A('| | Rev 7 (IPE 300 / 240) | Rev 7b (IPE 240 / 200) | **Rev 8 (continuous %s on %s)** |\n|---|---|---|---|' % (SR, SP))
A('| Steel for the offer, girts excluded | %s t | %s t | **%s t** |' % (f(S7['weight']['total_offer']/1000, 1), f(S7b['weight']['total_offer']/1000, 1), f(S['weight']['total_offer']/1000, 1)))
A('| Hot-rolled sections | %s t | %s t | **%s t** |' % (f(S7['weight']['sections_hot_rolled']/1000, 1), f(S7b['weight']['sections_hot_rolled']/1000, 1), f(S['weight']['sections_hot_rolled']/1000, 1)))
A('| Governing utilisation: beams / columns / bases / bays | %s / %s / %s / %s | %s / %s / %s / %s | **%s / %s / %s / %s** |' % tuple(f(x['max_util'][k], 2) for x in (S7, S7b, S) for k in ('beams', 'cols', 'bases', 'bays')))
A('| Seismic weight and design force | %s / %s kN | %s / %s kN | **%s / %s kN** |' % (f(S7['seismic']['W']), f(S7['seismic']['Fb_x']), f(S7b['seismic']['W']), f(S7b['seismic']['Fb_x']), f(S['seismic']['W']), f(S['seismic']['Fb_x'])))
A('')
A('## 2. Loads and combinations (load basis Rev 3, unchanged)\n')
A('G roof 0.37 kN/m2 (panel 0.12, purlins 0.05, services 0.10) + steel; G_min 0.17; Q 0.40 (cat. H, psi_0 = 0); wind v_b 27 m/s, z_e = h = 9 m, q_p by direction N 1.25 / E, W 1.05 / S 0.75 kN/m2, flat-roof zones with e = 18 m, c_pi +0.2 / -0.3, wall D +0.75 / E -0.40 / A -1.2 / B -0.8 / C -0.5; no wall self-weight (brief Rev 5), wall mass 0.30 kN/m2 in the seismic mass; seismic a_g 0.10 g, S 1.2, q 1.5, two-mass appendage amplification (resonance bound 5.5 alpha S = 0.66 g). Combinations EN 1990 6.10: ULS1 1.35 G + 1.5 Q, ULS2 1.35 G + 1.5 W_down, ULS3 1.0 G_min + 1.5 W_uplift per direction, ULS4 G + E (amplified, E_x + 0.3 E_y), thermal +/-30 K on the north bay pair, SLS G + Q and G + W_down, L/200 beams, L/150 purlins.\n')
A('Totals on the 20 columns (characteristic): G %s kN, Q %s, wind uplift N/S/E/W %s / %s / %s / %s, pressure %s kN; roof-level wind force N %s, S %s, E %s, W %s kN (char.); seismic weight %s kN, amplified design force %s kN in both directions (Rev 6a: %s kN on %s kN).\n' % (
    f(S['colsum']['G']), f(S['colsum']['Q']), f(S['colsum']['W_N']), f(S['colsum']['W_S']), f(S['colsum']['W_E']), f(S['colsum']['W_W']), f(S['colsum']['W_D']), f(S['wind_roof']['N']), f(S['wind_roof']['S']), f(S['wind_roof']['E']), f(S['wind_roof']['W']), f(S['seismic']['W']), f(S['seismic']['Fb_x']), f(S6['seismic']['Fb_x']), f(S6['seismic']['W'])))
A('## 3. Members (EN 1993-1-1; full list in members_C7.csv, plan in framing_C7.png)\n')
A('Sections: primaries and eave beams **%s** (P_K17K18 and P13 **IPE 330**), rafters, T3 and ST2 **%s**, columns and wind posts **%s**, S275; purlins Z200x2.0 @ 1.5 m; wall diagonals %s; roof rods %s.' % (SP, SR, SC, DG, RD) + ' Governing utilisations: beams %s, columns %s, bases %s, wall bays %s, roof rods %s, wind posts %s, diaphragm struts/chords %s, fin plates %s.\n' % tuple(f(S['max_util'][k], 2) for k in ('beams', 'cols', 'bases', 'bays', 'rods', 'wp', 'struts', 'fins')))
A('| Member | Span | Section | L m | M_Ed kNm | defl. mm / limit | util. | governs |\n|---|---|---|---|---|---|---|---|')
for b in S['beam_top'][:10]: A('| %s | %s | %s | %s | %s | %s / %s | %s | %s |' % (b['id'], b['span'], b['section'], f(b['L'], 2), f(b['M']), f(b['d']), f(b['dlim']), f(b['umax'], 2), b['gov']))
A('')
A('P_K17K18 (13.7 m eave, IPE 330): M_Ed %s kNm, deflection %s mm = L/%d under G + Q (L/200 = %s mm); top flange held by the four rafter seats at 2.6-2.9 m, bottom flange by fly braces at the rafters for the uplift case; as the E-W eave strut it carries the RT-E south reaction (%s kN) to B3: N + M interaction %s. P13 K19-K20 (9.8 m, IPE 330): %s. T3 (%s, 2.88 m) is the north chord of the RT-SW panel: %s. ST2 (%s, K15-R72): %s. Rafters: continuous over the y 29.3 line, hogging moment over the support checked for LTB of the bottom flange between the support and the first fly brace; worst rafter %s.\n' % (
    f(next(b['M'] for b in S['beam_top'] if b['id'] == 'P_K17K18')), f(next(b['d'] for b in S['beam_top'] if b['id'] == 'P_K17K18')), 13700/next(b['d'] for b in S['beam_top'] if b['id'] == 'P_K17K18'), f(13700/200), f(S['struts']['eave_strut_P_K17K18']['N']), f(S['struts']['eave_strut_P_K17K18']['u'], 2),
    next(r['utilisation'] for r in csv.DictReader(open(os.path.join(OUT, 'members_C7.csv'))) if r['id'] == 'P_K19K20/K19-K20'), SR, f(S['struts']['T3_chord']['u'], 2), SR, f(S['st2']['N']/S['st2']['Nb'], 2), ', '.join(['%s %s (%s)' % (b['id'], f(b['umax'], 2), b['gov']) for b in S['beam_top'] if b['section'] == SR][:2])))
A('Columns %s (6.3.3 with wall wind, bay compression and the amplified seismic case): worst %s; lengths L = cap-plate top - 0.065 (130 mm lower under the IPE 330 eaves): K19 %s, K17 %s, K6 %s, K1 %s m. Clear height under the cap-plate nuts at the north eave %s m.\n' % (SC, 
    ', '.join('%s %s' % (c, f(v['umax'], 2)) for c, v in sorted(S['cols'].items(), key=lambda kv: -kv[1]['umax'])[:4]), f(S['clear']['L_K19'], 3), f(S['clear']['L_K17'], 3), f(S['clear']['L_K6'], 3), f(S['clear']['L_K1'], 3), f(S['clear']['cap_nuts'], 2)))
A('Wind posts (HEA 140, base = centred 60 mm key 280 mm inboard of the face, shear only, slotted top connection so they carry no roof gravity): ' + '; '.join('%s on face %s, trib %s m, q %s kN/m2, M_Ed %s kNm, LTB %s, base shear %s kN (%s)' % (k, v['face'], f(v['trib']), f(v['q'], 2), f(v['My']), f(v['u'], 2), f(v['V']), f(v['u_base'], 2)) for k, v in S['wp'].items()) + '.\n')
A('Purlins Z200x2.0 @ 1.5 m: worst gravity moment %s kNm (limit 12.5 single / 16 sleeved) at %s, worst uplift %s kNm at %s (sleeved + anti-sag / fly braces as Rev 6a); longest span %s m, deflection %s mm (L/150 = %s). Rafter seat on the primary (web crippling): %s; cap plates: %s; strut / chord forces through the 2 M16 flange bolts: %s.\n' % (
    f(S['purlins']['Mg'], 2), 'x %s-%s, y %s' % tuple(f(v) for v in S['purlins']['Mg_where'][:3]), f(S['purlins']['Mu'], 2), 'x %s-%s, y %s' % tuple(f(v) for v in S['purlins']['Mu_where'][:3]), f(S['purlins']['Lmax'], 2), f(S['purlins']['d']), f(S['purlins']['dlim']), f(S['fin2']['umax'], 2), f(S['cap']['umax'], 2), f(S['max_util']['fins'], 2)))
A('## 4. Lateral system (seismic governs every bay, as in Rev 6a)\n')
A('| Bay | Columns | dir | w x h m | H_Ed kN (wind / seismic) | diagonal T kN | uplift N kN | %s util. (angle / bolts) | sway mm / lim |\n|---|---|---|---|---|---|---|---|---|' % DG)
for i, b in B.items(): A('| %s | %s | %s | %s x %s | %s (%s / %s) | %s | %s | %s | %s / %s |' % (i, '-'.join(next(bb for bb in [dict(B1=('K1','K2'),B2=('K5','K7'),B3=('K16','K17'),B5=('K15','K19'),B6=('K4','K14'),B7=('K16','K20'))[i]])), 'E-W' if i in ('B1','B2','B3') else 'N-S', f(b['w'], 2), f(b['h'], 2), f(b['H']), f(b['wind']), f(b['H4']), f(b['T']), f(b['N']), '%s / %s' % (f(b['util'], 2), f(b['util_bolt'], 2)), f(b['sway']), f(b['sway_lim'])))
A('')
A('| Roof strip | supports | end shear V kN | rod T kN | util. | deflection mm |\n|---|---|---|---|---|---|')
for t in S['trusses']: A('| %s | %s | %s | %s | %s | %s |' % (t['id'], {'RT-N-W': 'B5 - B7', 'RT-N-E': 'B7 - B6', 'RT-JOG': 'B7 (via R78)', 'RT-W': 'B3 (via P13, RT-SW) - B2', 'RT-SW': 'B3 (T3 -> K16)', 'RT-E': 'B3 (via eave strut) - B1'}[t['id']], f(t['V']), f(t['T']), f(t['util'], 2), f(t['delta'])))
A('')
A('Load paths: N-S inertia of the north strips to B5 (x 68), B7 (x 77.8, through R78 as a strut K10 -> K16) and B6 (x 95.5, straight into K4-K14); E-W inertia of the west block to B2 (north) and, through the west strip RT-W, the P13 eave strut and the RT-SW panel (T3 chord into K16), to B3; E-W inertia of the east block to B1 (north) and, through RT-E and the 13.7 m eave strut, to B3. Struts and chords: purlins %s, rafter chords %s, rafter N-S struts %s, R78 strut %s, y 29.3 primary chord %s. Drift (EN 1998-1 4.4.3.2, nu 0.5, 0.005 h): %s. Thermal lock-in on the north pair B1-B2: %s kN ULS with wind, %s kN erection state (as Rev 6a).\n' % (
    f(S['struts']['purlin']['u'], 2), f(S['struts']['rafter_chord']['u'], 2), f(S['struts']['rafter_strut']['u'], 2), f(S['struts']['R78_strut']['u'], 2), f(S['struts']['primary_chord']['u'], 2),
    ', '.join('%s %s' % (k, f(v['u'], 2)) for k, v in S['drift_eq'].items()), f(S['thermal']['F_uls_wind']), f(S['thermal']['F_uls_erect'])))
A('## 5. Bases (bases Rev 9 = Rev 8 detail on 20 columns; reactions per case in reactions_C7.csv)\n')
A('One base type at all 20 columns: plate 300 x 400 x 20 on a 25 mm grout bed, 4 post-installed dia 16 B500 rebars at 70 x 240 through the 300 mm slab (debonded) and 250-300 mm into the column head (EAD 330087 resin, rebar scan first), Key A SHS 90x90x8 in a cored, grouted pocket; inboard key pairs at %s; Key B (dia 60 bar) where an outward shear meets a free edge. Wind posts: centred 60 mm key only.\n' % ', '.join(c for c, e in S['base_env'].items() if e['pair']))
A('| Column | bays | N_c max kN (case) | N_t max kN (case) | V max kN | util. | governing check |\n|---|---|---|---|---|---|---|')
for c in ['K%d' % i for i in range(1, 21)]:
    e = S['base_env'][c]; A('| %s | %s | %s (%s) | %s (%s) | %s | %s | %s |' % (c, ', '.join(S['cols'][c]['bays']) or '-', f(e['Nc'][0]), e['Nc'][1], f(e['Nt'][0]), e['Nt'][1], f(e['Vt'][0]), f(e['umax'][0], 2), e['umax'][2]))
A('')
A('Highest: K14 %s (Key A parallel to the east edge, B6 shear; an inboard pair as at K4 would bring it to about 0.5), K16 %s (B3 + B7 corner, uplift %s kN: rebar bond %s), K17 %s, K4 %s (pair added in Rev 7). Rev 6a maximum was %s.\n' % (
    f(S['base_env']['K14']['umax'][0], 2), f(S['base_env']['K16']['umax'][0], 2), f(S['base_env']['K16']['Nt'][0]), f(S['base_env']['K16']['uten'], 2), f(S['base_env']['K17']['umax'][0], 2), f(S['base_env']['K4']['umax'][0], 2), f(S6['max_util']['bases'], 2)))
A('## 6. Sensitivities (not the binding basis; for the client\'s decisions)\n')
A('- (Sensitivities below were run on the Rev 7 heavy set; the margins of Rev 8 are similar and the conclusions hold.)')
A('- **Wind reference height 12.7 m** (the architect\'s levels put the hall at +8.10 and the roof top near +12.7 above the street; load basis Rev 3 assumed 9 m): q_p +8 %% and e = 25.4 m. All checks pass: beams %s, columns %s, bases %s, bays %s, wind posts %s. Recommendation: adopt in the next load-basis revision; no member changes.' % tuple(f(SZ['max_util'][k], 2) for k in ('beams', 'cols', 'bases', 'bays', 'wp')))
A('- **Gypsum walls 20 cm** (architect\'s wall schedule) instead of light panels: with 1.0 kN/m2 of wall (half of it acting at roof level because the wall heads are tied to the steel) the seismic weight rises from %s to %s kN and the design force to %s kN: bases K14 %s, K16 %s, K17 %s and bay B7 %s **fail**. Either the walls are light (<= 0.3 kN/m2 effective, as the brief assumes), or their heads are tied to the roof only for out-of-plane restraint through slotted connections that do not transfer the wall mass laterally, or the three bases get key pairs / larger keys and B7 gets 3 M20 gussets. To be settled with the wall system (brief: "later").' % (
    f(S['seismic']['W']), f(SW['seismic']['W']), f(SW['seismic']['Fb_x']), f(SW['base_env']['K14']['umax'][0], 2), f(SW['base_env']['K16']['umax'][0], 2), f(SW['base_env']['K17']['umax'][0], 2), f(max(SW['bays']['B7']['util'], SW['bays']['B7']['util_bolt']), 2)))
A('')
A('## 7. Drainage (unchanged, north)\n')
A('The roof still falls 6 %% north to the two external box gutters 150 x 100 on the north faces (y 35.37 west of the jog, y 35.87 east of it) with the four dia 100 downpipes DP1-DP4 on the north facade as in drainage_report.md. The catchment drops from 439 to %s m2 (west gutter about 137 m2, east gutter about 180 m2), so every reach, outlet and downpipe has more margin than before (worst outlet head about 45 mm at 100 mm/h); gutter section, falls, overflows and the stair-well outlet are kept. The south edges are verges with a drip flashing, no gutter. The light-well terrace keeps the existing slab drainage.\n' % f(S['roof_area'], 0))
A('## 8. Quantities (calc take-off; connection steel scaled from the Rev 6a BOM)\n')
A('| Item | Length m | kg |\n|---|---|---|')
A('| %s rafters (11 lines, continuous), T3, ST2 | %s | %s |' % (SR, f(L['rafters']), f(W['rafters'], 0)))
A('| %s primaries and eave beams | %s | %s |' % (SP, f(L['primaries_std']), f(W['primaries'] - L['primaries_IPE330']*49.1, 0)))
A('| IPE 330 eave beams P_K17K18 and P13 | %s | %s |' % (f(L['primaries_IPE330']), f(L['primaries_IPE330']*49.1, 0)))
A('| %s columns K1-K20 | %s | %s |' % (SC, f(L['columns']), f(L['columns']*24.7, 0)))
A('| %s wind posts WP2-WP4 | %s | %s |' % (SC, f(L['wind_posts']), f(L['wind_posts']*24.7, 0)))
A('| %s wall diagonals, 6 bays | %s | %s |' % (DG, f(L['wall_bracing']), f(W['wall_bracing'], 0)))
A('| %s roof rods, 12 panels | %s | %s |' % (RD, f(L['roof_bracing']), f(W['roof_bracing'], 0)))
A('| Z200x2.0 purlins @ 1.5 m (+3 %% anti-sag / eave rails) | %s | %s |' % (f(L['purlins'], 0), f(W['purlins_Z200'], 0)))
A('| Plates, cap/fin/gussets/cleats, keys, rebars, bolts (scaled allowance) | - | %s |' % f(W['plates_bolts_keys'], 0))
A('| **Steel in the offer** | | **%s t** |' % f(W['total_offer']/1000, 1))
A('| Z200 girts for panel walls (wall system open, not in the offer) | %s | %s |' % (f(L['girts'], 0), f(W['girts_Z200'], 0)))
A('')
A('Hot-rolled sections %s t (assembly rule base), roof panels %s m2 net.\n' % (f(W['sections_hot_rolled']/1000, 1), f(S['roof_area'], 0)))
A('## 9. Open items carried into the offer conditions\n')
A('1. Architect to redraw the 2nd level and the south elevation on the Rev 7 roof boundary (wall lines on the K19-K20 and K16-K17-K18 column lines), with the 6 % slope, the verge fascias and the north gutter/downpipes; confirm the six door-free braced bays.')
A('2. Wall system (gypsum vs light panel) and its head connection, see section 6; girts are not in the offer.')
A('3. Unchanged from Rev 6a: as-built slab data and level survey, column-head scans and cores, adequacy statement of the existing structure (now about %s kN gravity and %s kN roof-level seismic force), purlin supplier data, local wind/rain confirmation; the lift tower is a separate structure with a movement joint and flashing against the east roof edge.' % (f(1.0*S['colsum']['G'] + S['colsum']['Q'], 0), f(S['seismic']['Fb_x'], 0)))
open(os.path.join(OUT, 'design_report_C7_rev8.md'), 'w').write('\n'.join(Ls) + '\n')
print('written design_report_C7_rev8.md', len(Ls), 'lines')
