"""Writes rev6_vs_rev5.md: Rev 5a (IPE 330 / IPE 270 / HEA 160) vs Rev 6 (IPE 300 / IPE 240 / HEA 140) from summary_rev5_baseline.json and summary_C.json."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__)); OUT = os.path.join(HERE, '..')
a = json.load(open(os.path.join(HERE, 'summary_rev5_baseline.json'))); b = json.load(open(os.path.join(HERE, 'summary_C.json')))
f = lambda x, n=1: '%.*f' % (n, float(x))
rows = []
def add(item, va, vb, note=''): rows.append('| %s | %s | %s | %s |' % (item, va, vb, note))
def bt(s, i):
    return next((x for x in s.get('beam_top', []) if x['id'] == i), None)
add('Sections primaries / rafters / columns', 'IPE 330 / IPE 270 / HEA 160', 'IPE 300 / IPE 240 / HEA 140, P13 (K19-K20) IPE 330', 'brief Rev 7, client decision; Rev 6a: P13 kept IPE 330 (review A2)')
add('Levels: primary top / column top / column length', 'TOS + 0.05 / TOS - 0.30 / TOS - 0.35', 'TOS + 0.03 / TOS - 0.29 / TOS - 0.335 exact (K19, K20: - 0.32 / - 0.365)', 'Rev 6a (A1): the TOS + 0.05 of Rev 3-6 put the rafter flange 0.7-4.3 mm below the primary flange; now 19.3 mm clear')
add('Clear height under the cap nuts (y 35.77) / eave primary / rafters at the north edge, m', '3.02 / 3.06 / 3.06 (as printed; the true Rev 5 values were 3.00 / 3.04 / 3.06 with the flange clash)', '%s / %s / %s' % (f(b['clear']['cap_nuts'], 2), f(b['clear']['primary_bottom'], 2), f(b['clear']['rafter_N'], 2)))
add('Seismic mass W_a kN / F E-W / F N-S kN (two-mass, q 1.5)', '%s / %s / %s' % (f(a['seismic']['W'], 0), f(a['seismic']['Fb_x'], 0), f(a['seismic']['Fb_y'], 0)), '%s / %s / %s' % (f(b['seismic']['W'], 0), f(b['seismic']['Fb_x'], 0), f(b['seismic']['Fb_y'], 0)), 'lighter roof steel')
add('Max beam utilisation (K19-K20 primary)', '%s (%s)' % (f(a['max_util']['beams'], 2), 'LTB gravity'), '%s (%s)' % (f(b['max_util']['beams'], 2), bt(b, 'P_K19K20')['gov']), 'Rev 6 envelopes G + Q and G + 0.5 q_p (pressure case) for L/200; P13 IPE 330 (Rev 6a)')
k = bt(b, 'P_K19K20'); add('K19-K20 (9.79 m): LTB gravity / deflection mm (L/x) [case]', '0.68 / 26.9 (L/364) [G+Q]', '%s / %s (L/%s) [%s] as IPE 330; as IPE 300: 0.82 / 46.0 (L/213)' % (f(k['u']['LTBg'], 2), f(k['d']), f(9790/k['d'], 0), k['dcase']), 'Rev 5 checked G + Q only')
r9 = max((x for x in b['beam_top'] if x['L'] > 9 and x['section'] == b['secs']['raft']), key=lambda x: x['umax']); add('9.2 m rafters: utilisation (governs) / LTB uplift / deflection mm (L/x)', '0.55 (M) / 0.47 / 25.4 (L/362)', '%s (%s) / %s / %s (L/%s) [%s]' % (f(r9['umax'], 2), r9['gov'], f(r9['u']['LTBu'], 2), f(r9['d']), f(9200/r9['d'], 0), r9['dcase']), 'two fly braces at the third points, unchanged')
add('Max column utilisation (K25, corner, biaxial)', '%s' % f(a['max_util']['cols'], 2), '%s (%s, k_zy %s)' % (f(b['max_util']['cols'], 2), b['cols']['K25']['case'], f(b['cols']['K25']['kzy'], 2)), 'HEA 140: 1.06 only at load basis Rev 2 wind')
add('Column N_b,Rd range kN', '461-667 (HEA 160)', '%s-%s' % (f(min(c['NbRd'] for c in b['cols'].values()), 0), f(max(c['NbRd'] for c in b['cols'].values()), 0)))
add('Wind post WP1', '%s' % f(a['wp1']['u'], 2), '%s' % f(b['wp1']['u'], 2))
add('Posts ST1 / ST2', '%s / %s' % (f(a['st']['N1']/a['st']['Nb1'], 2), f(a['st']['N2']/a['st']['Nb2'], 2)), '%s / %s' % (f(b['st']['N1']/b['st']['Nb1'], 2), f(b['st']['N2']/b['st']['Nb2'], 2)))
for i in ('B1', 'B2', 'B3', 'B5', 'B7'):
    add('Bay %s: H_Ed kN (seismic) / diagonal' % i, '%s / %s' % (f(a['bays'][i]['H']), f(a['bays'][i]['util'], 2)), '%s / %s' % (f(b['bays'][i]['H']), f(b['bays'][i]['util'], 2)))
add('Roof rods: worst (jog) / RT-W chord kN in the rafters', '%s / %s' % (f(max(x['util'] for x in a['trusses']), 2), f(next(x['chord'] for x in a['trusses'] if x['id'] == 'RT-W'))), '%s / %s' % (f(max(x['util'] for x in b['trusses']), 2), f(next(x['chord'] for x in b['trusses'] if x['id'] == 'RT-W'))))
add('Strut / chord members (axial + bending): rafter chord / rafter N-S strut / primary chord', '%s / %s / %s' % (f(a['struts']['rafter_chord']['u'], 2), f(a['struts']['rafter_strut']['u'], 2), f(a['struts']['primary_chord']['u'], 2)), '%s / %s / %s' % (f(b['struts']['rafter_chord']['u'], 2), f(b['struts']['rafter_strut']['u'], 2), f(b['struts']['primary_chord']['u'], 2)))
add('Fin plates: web bearing per M20 (one row) / worst strut splice / chord splices', '68.8 kN / %s (R78, 2 M20) / 3 M20 <= %s' % (f(next(x['umax'] for x in a['fins'] if x['member'] == 'R78'), 2), f(max(x['umax'] for x in a['fins'] if x['n'] == 3), 2)), '%s kN / %s (R78, 2 M20) / 2 x 2 M20 <= %s' % (f(next(x['FbRd'] for x in b['fins'] if x['cols'] == 1)), f(next(x['umax'] for x in b['fins'] if x['member'] == 'R78'), 2), f(max(x['umax'] for x in b['fins'] if x['cols'] == 2), 2)), 'IPE 240 web 6.2 mm, 190 clear: no 3-bolt row')
add('Gravity fin plate (2 M20) / cap plate worst / cap-plate cantilever', '%s / %s / -' % (f(a['fin2']['umax'], 2), f(a['cap']['umax'], 2)), '%s / %s / %s' % (f(b['fin2']['umax'], 2), f(b['cap']['umax'], 2), f(b['cap']['util']['cap plate cantilever'], 2)), 'HEA 140: gauge 90 inside the 140 flange, pitch 200 outside the 133 depth')
add('Seismic drift nu d_r vs 0.005 h, west wall / x 77.8 line, mm', '%s / %s vs %s' % (f(a['drift_eq']['west wall (RT-W + B4/B2)']['dr_nu']), f(a['drift_eq']['x 77.8 line (jog + R78 + B7)']['dr_nu']), f(a['drift_eq']['west wall (RT-W + B4/B2)']['lim'])), '%s / %s vs %s' % (f(b['drift_eq']['west wall (RT-W + B4/B2)']['dr_nu']), f(b['drift_eq']['x 77.8 line (jog + R78 + B7)']['dr_nu']), f(b['drift_eq']['west wall (RT-W + B4/B2)']['lim'])))
add('Thermal path k_eff kN/mm / F ULS wind / erection kN', '%s / %s / %s' % (f(a['thermal']['keff'], 1), f(a['thermal']['F_uls_wind'], 0), f(a['thermal']['F_uls_erect'], 0)), '%s / %s / %s' % (f(b['thermal']['keff'], 1), f(b['thermal']['F_uls_wind'], 0), f(b['thermal']['F_uls_erect'], 0)))
add('Sum G on the bases, char. kN', f(sum(v['G'] for v in a['colloads'].values()), 0), f(sum(v['G'] for v in b['colloads'].values()), 0))
for c in ('K7', 'K19', 'K23', 'K22', 'K20', 'K27', 'K14', 'K25'):
    ea, eb = a['base_env'][c], b['base_env'][c]
    add('%s: N_t max kN (case) / N_c max / V max / base util.' % c, '%s (%s) / %s / %s / %s' % (f(max(ea['Nt'][0], 0)), ea['Nt'][1], f(ea['Nc'][0]), f(ea['Vt'][0]), f(ea['umax'][0], 2)), '%s (%s) / %s / %s / %s' % (f(max(eb['Nt'][0], 0)), eb['Nt'][1], f(eb['Nc'][0]), f(eb['Vt'][0]), f(eb['umax'][0], 2)))
add('Bases: tension max / key max / plate max / worst', '%s / %s / %s / %s (%s)' % (f(max(e['uten'] for e in a['base_env'].values()), 2), f(max(e['ukey'] for e in a['base_env'].values()), 2), f(max(e['uplate'] for e in a['base_env'].values()), 2), f(a['max_util']['bases'], 2), max(a['base_env'], key=lambda c: a['base_env'][c]['umax'][0])),
    '%s / %s / %s / %s (%s)' % (f(max(e['uten'] for e in b['base_env'].values()), 2), f(max(e['ukey'] for e in b['base_env'].values()), 2), f(max(e['uplate'] for e in b['base_env'].values()), 2), f(b['max_util']['bases'], 2), max(b['base_env'], key=lambda c: b['base_env'][c]['umax'][0])), 'base plates 25 -> 20 mm; rebars and keys unchanged')
Wa, Wb = a['weight'], b['weight']
add('Weight t: rafters / primaries / columns / bracing / plates', '%s / %s / %s / %s / %s' % (f(Wa['rafters']/1000, 2), f(Wa['primaries']/1000, 2), f(Wa['columns']/1000, 2), f((Wa['wall_bracing'] + Wa['roof_bracing'])/1000, 2), f(Wa['plates_bolts_keys']/1000, 2)), '%s / %s / %s / %s / %s' % (f(Wb['rafters']/1000, 2), f(Wb['primaries']/1000, 2), f(Wb['columns']/1000, 2), f((Wb['wall_bracing'] + Wb['roof_bracing'])/1000, 2), f(Wb['plates_bolts_keys']/1000, 2)))
add('Weight: calc take-off / BOM basis t', '%s / %s (25.4 less the Rev 5 bracing)' % (f(Wa['total']/1000, 1), f((Wa['BOM_total'] - 830)/1000, 1)), '%s / **%s**' % (f(Wb['total']/1000, 1), f(Wb['BOM_total']/1000, 1)), 'sections -%s t (P13 IPE 330 kept, +0.07), bracing -0.83 t, plates -0.13 t' % f((Wa['rafters'] + Wa['primaries'] + Wa['columns'] - Wb['rafters'] - Wb['primaries'] - Wb['columns'])/1000, 2))
md = ['# Design C: Rev 6a (IPE 300 / IPE 240 / HEA 140, P13 IPE 330, levels per A1) versus Rev 5a (IPE 330 / IPE 270 / HEA 160) - one-page comparison\n',
      'Same scripts (`calc/run_all.py`), load basis Rev 3, Rev 5a bracing; Rev 5a values from `calc/summary_rev5_baseline.json`, Rev 6 from `calc/summary_C.json`. ULS unless stated; kN, kNm, mm.\n',
      '| Item | Rev 5a | Rev 6 | Note |', '|---|---|---|---|'] + rows + [
      '\nExceptions: P13 (K19-K20, 9.79 m) kept as IPE 330 on the reviewer\'s recommendation (Rev 6a) - as IPE 300 it passed at 0.94 with a precamber; every other member, connection and base passes with the lighter section, no precamber anywhere (P13 L/%s under the pressure case); the SW corner column K25 (0.80) is the member closest to its limit. Not changed: geometry and roof plane, bracing layout (13 panels, 8 bays), rods and angles, the base detail (rebars, keys, key pairs), the detailing package (S00-S06 to be re-issued for the new sections, levels and plates).' % f(9790/k['d'], 0)]
open(os.path.join(OUT, 'rev6_vs_rev5.md'), 'w').write('\n'.join(md) + '\n')
print('rev6_vs_rev5.md written')
